name: A1 Sniper

on:
  workflow_dispatch: # Allows you to start it manually
  schedule:
    - cron: '*/5 * * * *' # This is the "Magic" line that repeats it every 5 minutes

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-interaction

      - name: Create Private Key File
        run: echo "${{ secrets.OCI_PRIVATE_KEY }}" > oci_api_key.pem

      - name: Snipe
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ./oci_api_key.pem 
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_BOOT_VOLUME_SIZE_IN_GBS: 50
        run: php index.php
