name: A1 Sniper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Uses the newest version
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          # This line below forces it to NOT use the broken cache service
          cache: none 
          
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Sniper Script
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
        run: php index.php
